
// might chnage id & userID
const defaultWelcomeMarkdownData = {
  id: "100000000",
  userId: "100000000",
  createdAt: "04-01-2022",
  name: "welcome-default.md",
  content:
    "# Welcome to *Markdown*\n\nMarkdown is a lightweight markup language that you can use to add formatting elements to plaintext text documents.\n\n## How to use this?\n\n1. Write markdown in the markdown editor window\n2. See the rendered markdown in the preview window\n\n### Features\n\n- Create headings, paragraphs, links, blockquotes, inline-code, code blocks, and lists\n- Name and save the document to access again later\n- Choose between Light or Dark mode depending on your preference\n\n> This is an example of a blockquote. If you would like to learn more about markdown syntax, you can visit this [markdown cheatsheet](https://www.markdownguide.org/cheat-sheet/).\n\n#### Headings\n\nTo create a heading, add the hash sign (#) before the heading. The number of number signs you use should correspond to the heading level. You'll see in this guide that we've used all six heading levels (not necessarily in the correct way you should use headings!) to illustrate how they should look.\n\n##### Lists\n\nYou can see examples of ordered and unordered lists above.\n\n###### Code Blocks\n\nThis markdown editor allows for inline-code snippets, like this: `<p>I'm inline</p>`. It also allows for larger code blocks like this:\n\n```\n<main>\n  <h1>This is a larger code block</h1>\n</main>\n```\n\n * Lists\n\n * [ ] todo\n\n * [x] done\n\n\n## Image and Link Examples\n\n\n![Design preview for the In-browser markdown editor coding challenge](https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)\n\n\n<img src='https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29kaW5nfGVufDB8fDB8fHwy' alt='laptop-image-example'/>\n\n\n- Image-1: [Image Example 1](https://unsplash.com/photos/macbook-pro-on-brown-wooden-table-SyYmXSDnJ54)\n- Image-2:[Image example 2](https://unsplash.com/photos/lines-of-html-codes-4hbJ-eymZ1o)",
};

export default defaultWelcomeMarkdownData